// Auto-generated by deploy script
export const CONTRACTS = {
  "deployerWalletAddress": "0xacd4595199345e43a09ed83b067c90b3afcc2cb4",
  "personalWalletAddress": "0x078267C2B4f88822a59Ba17972ddC5006032fAd1",
  "gameEngineAddress": "0x3FD47Aa00237e644D7C03B6090076Dc5d58A69CC",
  "playerNFTAddress": "0x7Ef1976b1cCd5C5853D9B23b8B05026f13cD5D3a",
  "factoryAddress": "0xB83Ac8C5c46073Bcc957Bffe5EBD5AbfE2a91937"
};
