// Auto-generated by deploy script
export const CONTRACTS = {
  "gameRegistryAddress": "0x73Ea2a964B1dd4D815d20e2c2b717f69ddb3e9E6",
  "personalWalletAddress": "0x078267C2B4f88822a59Ba17972ddC5006032fAd1",
  "gameEngineAddress": "0x4383611e0a47C67e3abe174bF6b19E315251595C"
};
